spritegen: spritegen.c
	gcc -o spritegen spritegen.c

spritegen2: spritegen2.c
	gcc -o spritegen2 spritegen2.c

spritegen_encoded: spritegen_encoded.c
	gcc -o spritegen_encoded spritegen_encoded.c

fontgen: fontgen.c
	gcc -o fontgen fontgen.c

palettegen: palettegen.c
	gcc -o palettegen palettegen.c